name: Classes
main: com.biteforcemc.classes.Main
version: v0.1
author: Zack
description: view and set classes.
softdepend: [PlaceholderAPI]
commands:
  classes:
    description: view classes
